using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using Godot;
using MegaCrit.Sts2.Core.Assets;
using MegaCrit.Sts2.Core.Audio.Debug;
using MegaCrit.Sts2.Core.Debug;
using MegaCrit.Sts2.Core.Localization;
using MegaCrit.Sts2.Core.Nodes;
using MegaCrit.Sts2.Core.Nodes.Animation;
using MegaCrit.Sts2.Core.Nodes.Audio;
using MegaCrit.Sts2.Core.Nodes.Cards;
using MegaCrit.Sts2.Core.Nodes.Cards.Holders;
using MegaCrit.Sts2.Core.Nodes.Combat;
using MegaCrit.Sts2.Core.Nodes.CommonUi;
using MegaCrit.Sts2.Core.Nodes.Debug;
using MegaCrit.Sts2.Core.Nodes.Debug.Multiplayer;
using MegaCrit.Sts2.Core.Nodes.Events;
using MegaCrit.Sts2.Core.Nodes.Events.Custom;
using MegaCrit.Sts2.Core.Nodes.Events.Custom.CrystalSphere;
using MegaCrit.Sts2.Core.Nodes.Ftue;
using MegaCrit.Sts2.Core.Nodes.GodotExtensions;
using MegaCrit.Sts2.Core.Nodes.HoverTips;
using MegaCrit.Sts2.Core.Nodes.Multiplayer;
using MegaCrit.Sts2.Core.Nodes.Orbs;
using MegaCrit.Sts2.Core.Nodes.Potions;
using MegaCrit.Sts2.Core.Nodes.Reaction;
using MegaCrit.Sts2.Core.Nodes.Relics;
using MegaCrit.Sts2.Core.Nodes.RestSite;
using MegaCrit.Sts2.Core.Nodes.Rewards;
using MegaCrit.Sts2.Core.Nodes.Rooms;
using MegaCrit.Sts2.Core.Nodes.Screens;
using MegaCrit.Sts2.Core.Nodes.Screens.Bestiary;
using MegaCrit.Sts2.Core.Nodes.Screens.Capstones;
using MegaCrit.Sts2.Core.Nodes.Screens.CardLibrary;
using MegaCrit.Sts2.Core.Nodes.Screens.CardSelection;
using MegaCrit.Sts2.Core.Nodes.Screens.CharacterSelect;
using MegaCrit.Sts2.Core.Nodes.Screens.Credits;
using MegaCrit.Sts2.Core.Nodes.Screens.CustomRun;
using MegaCrit.Sts2.Core.Nodes.Screens.DailyRun;
using MegaCrit.Sts2.Core.Nodes.Screens.FeedbackScreen;
using MegaCrit.Sts2.Core.Nodes.Screens.GameOverScreen;
using MegaCrit.Sts2.Core.Nodes.Screens.InspectScreens;
using MegaCrit.Sts2.Core.Nodes.Screens.MainMenu;
using MegaCrit.Sts2.Core.Nodes.Screens.Map;
using MegaCrit.Sts2.Core.Nodes.Screens.ModdingScreen;
using MegaCrit.Sts2.Core.Nodes.Screens.Overlays;
using MegaCrit.Sts2.Core.Nodes.Screens.PauseMenu;
using MegaCrit.Sts2.Core.Nodes.Screens.PotionLab;
using MegaCrit.Sts2.Core.Nodes.Screens.ProfileScreen;
using MegaCrit.Sts2.Core.Nodes.Screens.RelicCollection;
using MegaCrit.Sts2.Core.Nodes.Screens.RunHistoryScreen;
using MegaCrit.Sts2.Core.Nodes.Screens.Settings;
using MegaCrit.Sts2.Core.Nodes.Screens.Shops;
using MegaCrit.Sts2.Core.Nodes.Screens.StatsScreen;
using MegaCrit.Sts2.Core.Nodes.Screens.Timeline;
using MegaCrit.Sts2.Core.Nodes.Screens.Timeline.UnlockScreens;
using MegaCrit.Sts2.Core.Nodes.Screens.TreasureRoomRelic;
using MegaCrit.Sts2.Core.Nodes.TopBar;
using MegaCrit.Sts2.Core.Nodes.TreasureRooms;
using MegaCrit.Sts2.Core.Nodes.Vfx;
using MegaCrit.Sts2.Core.Nodes.Vfx.Backgrounds;
using MegaCrit.Sts2.Core.Nodes.Vfx.Cards;
using MegaCrit.Sts2.Core.Nodes.Vfx.Events;
using MegaCrit.Sts2.Core.Nodes.Vfx.Examples;
using MegaCrit.Sts2.Core.Nodes.Vfx.Ui;
using MegaCrit.Sts2.Core.Nodes.Vfx.Utilities;
using MegaCrit.Sts2.Core.RichTextTags;
using MegaCrit.Sts2.Core.Timeline;
using MegaCrit.Sts2.GameInfo;
using MegaCrit.Sts2.addons.mega_text;
using MegaCrit.sts2.Core.Nodes.TopBar;
using RiderTestRunner;

[assembly: AssemblyMetadata("Sentry.ProjectDirectory", "/builds/megacrit/sts2/sts2/sts2/")]
[assembly: AssemblyCompany("Mega Crit Games")]
[assembly: AssemblyConfiguration("ExportRelease")]
[assembly: AssemblyCopyright("© 2023 Mega Crit Games")]
[assembly: AssemblyDescription("sts2")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0+cb602cefd883e8595b7f709863489a88c2a32765")]
[assembly: AssemblyProduct("sts2")]
[assembly: AssemblyTitle("sts2")]
[assembly: AssemblyHasScripts(new Type[]
{
	typeof(MegaLabel),
	typeof(MegaRichTextLabel),
	typeof(CiCoreRunner),
	typeof(NetCoreRunner),
	typeof(AtlasResourceLoader),
	typeof(NDebugAudioManager),
	typeof(DebugActMap),
	typeof(NBgLayerDebug),
	typeof(NCombatVfxSpawner),
	typeof(NDebugVfxSpawner),
	typeof(NTrailTest),
	typeof(LocTextLabel),
	typeof(NDecimillipedeSegmentDriver),
	typeof(NSpineAutoPlayer),
	typeof(NAudioManager),
	typeof(NRunMusicController),
	typeof(NCardHolder),
	typeof(NCardHolderHitbox),
	typeof(NGridCardHolder),
	typeof(NHandCardHolder),
	typeof(NPreviewCardHolder),
	typeof(NSelectedHandCardHolder),
	typeof(NCard),
	typeof(NCardBundle),
	typeof(NCardGrid),
	typeof(NCardHighlight),
	typeof(NEnchantPreview),
	typeof(NTinyCard),
	typeof(NTransformPreview),
	typeof(NUpgradePreview),
	typeof(NCardPlay),
	typeof(NCardPlayQueue),
	typeof(NCombatCardPile),
	typeof(NCombatPilesContainer),
	typeof(NCombatSceneContainer),
	typeof(NCombatStartBanner),
	typeof(NCombatUi),
	typeof(NControllerCardPlay),
	typeof(NCreature),
	typeof(NCreatureStateDisplay),
	typeof(NCreatureVisuals),
	typeof(NDiscardPileButton),
	typeof(NDrawPileButton),
	typeof(NEndTurnButton),
	typeof(NEndTurnLongPressBar),
	typeof(NEnemyTurnBanner),
	typeof(NEnergyCounter),
	typeof(NExhaustPileButton),
	typeof(NHealthBar),
	typeof(NIntent),
	typeof(NMouseCardPlay),
	typeof(NPeekButton),
	typeof(NPingButton),
	typeof(NPlayerHand),
	typeof(NPlayerTurnBanner),
	typeof(NPower),
	typeof(NPowerContainer),
	typeof(NRemoteTargetingIndicator),
	typeof(NSelectedHandCardContainer),
	typeof(NSelectionReticle),
	typeof(NStarCounter),
	typeof(NTargetingArrow),
	typeof(NTargetManager),
	typeof(NAbandonRunConfirmPopup),
	typeof(NBackButton),
	typeof(NCardPreviewContainer),
	typeof(NCardViewSortButton),
	typeof(NCommonBanner),
	typeof(NConfirmButton),
	typeof(NControllerManager),
	typeof(NCursorManager),
	typeof(NDisconnectConfirmPopup),
	typeof(NDropdownContainer),
	typeof(NDropdownItem),
	typeof(NDropdownScrollbar),
	typeof(NErrorPopup),
	typeof(NGlobalUi),
	typeof(NGoldArrowButton),
	typeof(NGridCardPreviewContainer),
	typeof(NHotkeyManager),
	typeof(NInputManager),
	typeof(NLoadingOverlay),
	typeof(NMessyCardPreviewContainer),
	typeof(NMiscConfirmButton),
	typeof(NModalContainer),
	typeof(NMultiplayerVoteContainer),
	typeof(NPopupYesNoButton),
	typeof(NProceedButton),
	typeof(NSaveIndicator),
	typeof(NScrollbarTrain),
	typeof(NSearchBar),
	typeof(NSettingsScreenPopup),
	typeof(NTickbox),
	typeof(NTopBar),
	typeof(NVerticalPopup),
	typeof(NMultiplayerTest),
	typeof(NMultiplayerTestCharacterPaginator),
	typeof(NCommandHistory),
	typeof(NDebugAspectRatio),
	typeof(NDebugInfoLabelManager),
	typeof(NDevConsole),
	typeof(NFpsVisualizer),
	typeof(NMemoryMonitor),
	typeof(NParticleCounter),
	typeof(NSceneBootstrapper),
	typeof(NCrystalSphereCell),
	typeof(NCrystalSphereDialogue),
	typeof(NCrystalSphereItem),
	typeof(NCrystalSphereMask),
	typeof(NCrystalSphereScreen),
	typeof(NFakeMerchant),
	typeof(NAncientDialogueHitbox),
	typeof(NAncientDialogueLine),
	typeof(NAncientEventLayout),
	typeof(NCombatEventLayout),
	typeof(NDivinationButton),
	typeof(NEventLayout),
	typeof(NEventOptionButton),
	typeof(NAcceptTutorialsFtue),
	typeof(NCannotPlayCardFtue),
	typeof(NCanPlayCardsFtue),
	typeof(NCombatRewardFtue),
	typeof(NCombatRulesFtue),
	typeof(NFtue),
	typeof(NFtueConfirmButton),
	typeof(NMapSelectFtue),
	typeof(NMerchantFtue),
	typeof(NObtainPotionFtue),
	typeof(NPowerCardFtue),
	typeof(NRelicRewardFtue),
	typeof(NRestSiteFtue),
	typeof(NShuffleFtue),
	typeof(NButton),
	typeof(NClickableControl),
	typeof(NDropdown),
	typeof(NMegaLineEdit),
	typeof(NMegaTextEdit),
	typeof(NScrollableContainer),
	typeof(NScrollbar),
	typeof(NSlider),
	typeof(NHoverTipCardContainer),
	typeof(NHoverTipSet),
	typeof(NMapPointHistoryHoverTip),
	typeof(NGenericPopup),
	typeof(NInvitePlayersButton),
	typeof(NMultiplayerCardIntent),
	typeof(NMultiplayerNetworkProblemIndicator),
	typeof(NMultiplayerPlayerExpandedState),
	typeof(NMultiplayerPlayerIntentHandler),
	typeof(NMultiplayerPlayerState),
	typeof(NMultiplayerPlayerStateContainer),
	typeof(NMultiplayerTimeoutOverlay),
	typeof(NMultiplayerWarningPopup),
	typeof(NRemoteLoadLobbyPlayerContainer),
	typeof(NRemoteLobbyPlayer),
	typeof(NRemoteLobbyPlayerContainer),
	typeof(NRemoteMouseCursor),
	typeof(NRemoteMouseCursorContainer),
	typeof(NActBanner),
	typeof(NAncientNameBanner),
	typeof(NAssetLoader),
	typeof(NBackgroundModeHandler),
	typeof(NGame),
	typeof(NMuteInBackgroundHandler),
	typeof(NOneTimeInitialization),
	typeof(NRun),
	typeof(NSceneContainer),
	typeof(NTransition),
	typeof(NOrb),
	typeof(NOrbManager),
	typeof(NPotion),
	typeof(NPotionContainer),
	typeof(NPotionHolder),
	typeof(NPotionPopup),
	typeof(NPotionPopupButton),
	typeof(NPotionShortcutButton),
	typeof(NReaction),
	typeof(NReactionContainer),
	typeof(NReactionWheel),
	typeof(NReactionWheelWedge),
	typeof(NRelic),
	typeof(NRelicBasicHolder),
	typeof(NRelicInventory),
	typeof(NRelicInventoryHolder),
	typeof(NParticleSystemUpscaler),
	typeof(NRestSiteButton),
	typeof(NRestSiteCharacter),
	typeof(NLinkedRewardSet),
	typeof(NRewardButton),
	typeof(NCombatBackground),
	typeof(NCombatRoom),
	typeof(NEventRoom),
	typeof(NMapRoom),
	typeof(NMerchantButton),
	typeof(NMerchantRoom),
	typeof(NRestSiteRoom),
	typeof(NTreasureRoom),
	typeof(NBestiary),
	typeof(NBestiaryEntry),
	typeof(NBestiaryMoveButton),
	typeof(NCapstoneContainer),
	typeof(NCardCostTickbox),
	typeof(NCardLibrary),
	typeof(NCardLibraryGrid),
	typeof(NCardLibraryStats),
	typeof(NCardPoolFilter),
	typeof(NCardRarityTickbox),
	typeof(NCardTypeTickbox),
	typeof(NClearSearchButton),
	typeof(NLibraryStatTickbox),
	typeof(NCardGridSelectionScreen),
	typeof(NCardRewardAlternativeButton),
	typeof(NCardRewardSelectionScreen),
	typeof(NChoiceSelectionSkipButton),
	typeof(NChooseABundleSelectionScreen),
	typeof(NChooseACardSelectionScreen),
	typeof(NDeckCardSelectScreen),
	typeof(NDeckEnchantSelectScreen),
	typeof(NDeckTransformSelectScreen),
	typeof(NDeckUpgradeSelectScreen),
	typeof(NSimpleCardSelectScreen),
	typeof(NActDropdown),
	typeof(NAscensionPanel),
	typeof(NCharacterSelectButton),
	typeof(NCharacterSelectScreen),
	typeof(NCharacterSelectScreenBg),
	typeof(NMultiplayerLoadGameScreen),
	typeof(NRegentCharacterSelectBg),
	typeof(NCreditsScreen),
	typeof(NCustomRunLoadScreen),
	typeof(NCustomRunScreen),
	typeof(NRunModifierTickbox),
	typeof(NDailyRunCharacterContainer),
	typeof(NDailyRunLeaderboard),
	typeof(NDailyRunLeaderboardRow),
	typeof(NDailyRunLeaderboardSeparator),
	typeof(NDailyRunLoadScreen),
	typeof(NDailyRunScoreWarning),
	typeof(NDailyRunScreen),
	typeof(NDailyRunScreenModifier),
	typeof(NLeaderboardDayPaginator),
	typeof(NLeaderboardPageArrow),
	typeof(NFeedbackCategoryDropdown),
	typeof(NFeedbackCategoryDropdownItem),
	typeof(NFeedbackScreenOpener),
	typeof(NSendFeedbackButton),
	typeof(NSendFeedbackCartoon),
	typeof(NSendFeedbackEmojiButton),
	typeof(NSendFeedbackFlower),
	typeof(NSendFeedbackScreen),
	typeof(NBadge),
	typeof(NDiscoveredItem),
	typeof(NGameOverContinueButton),
	typeof(NGameOverScreen),
	typeof(NReturnToMainMenuButton),
	typeof(NRunSummary),
	typeof(NViewRunButton),
	typeof(NInspectRelicScreen),
	typeof(NUpgradePreviewTickbox),
	typeof(NCompendiumBottomButton),
	typeof(NCompendiumSubmenu),
	typeof(NContinueRunInfo),
	typeof(NCustomRunModifiersList),
	typeof(NDisclaimerProceedButton),
	typeof(NEarlyAccessDisclaimer),
	typeof(NJoinFriendButton),
	typeof(NJoinFriendRefreshButton),
	typeof(NJoinFriendScreen),
	typeof(NJoinFriendScreenButtonLayout),
	typeof(NLogoAnimation),
	typeof(NMainMenu),
	typeof(NMainMenuBg),
	typeof(NMainMenuContinueButton),
	typeof(NMainMenuSubmenuStack),
	typeof(NMainMenuTextButton),
	typeof(NMultiplayerHostSubmenu),
	typeof(NMultiplayerSubmenu),
	typeof(NOpenProfileScreenButton),
	typeof(NPatchNotesButton),
	typeof(NPatchNotesScreen),
	typeof(NPrideRainbow),
	typeof(NShortSubmenuButton),
	typeof(NSingleplayerSubmenu),
	typeof(NSubmenu),
	typeof(NSubmenuButton),
	typeof(NSubmenuStack),
	typeof(NAncientMapPoint),
	typeof(NBaseMapDrawingButton),
	typeof(NBossMapPoint),
	typeof(NControllerMapDrawingInput),
	typeof(NMapBg),
	typeof(NMapClearButton),
	typeof(NMapDrawButton),
	typeof(NMapDrawingInput),
	typeof(NMapDrawings),
	typeof(NMapEraseButton),
	typeof(NMapLegendItem),
	typeof(NMapMarker),
	typeof(NMapPoint),
	typeof(NMapScreen),
	typeof(NMouseHeldMapDrawingInput),
	typeof(NMouseModeMapDrawingInput),
	typeof(NNormalMapPoint),
	typeof(NConfirmModLoadingPopup),
	typeof(NModdingScreen),
	typeof(NModInfoContainer),
	typeof(NModMenuButton),
	typeof(NModMenuRow),
	typeof(NAncientBgContainer),
	typeof(NCapstoneSubmenuStack),
	typeof(NCardPileScreen),
	typeof(NCardsViewScreen),
	typeof(NChooseARelicSelection),
	typeof(NDeckViewScreen),
	typeof(NInspectCardScreen),
	typeof(NRewardsScreen),
	typeof(NRunSubmenuStack),
	typeof(NShareButton),
	typeof(NSimpleCardsViewScreen),
	typeof(NOverlayStack),
	typeof(NPauseMenu),
	typeof(NPauseMenuButton),
	typeof(NLabPotionHolder),
	typeof(NPotionLab),
	typeof(NPotionLabCategory),
	typeof(NDeleteProfileButton),
	typeof(NProfileButton),
	typeof(NProfileIcon),
	typeof(NProfileScreen),
	typeof(NRelicCollection),
	typeof(NRelicCollectionCategory),
	typeof(NRelicCollectionEntry),
	typeof(NActHistoryEntry),
	typeof(NDeckHistory),
	typeof(NDeckHistoryEntry),
	typeof(NMapPointHistory),
	typeof(NMapPointHistoryEntry),
	typeof(NRelicHistory),
	typeof(NRunHistory),
	typeof(NRunHistoryArrowButton),
	typeof(NRunHistoryPlayerIcon),
	typeof(NAbandonRunButton),
	typeof(NAmbienceSlider),
	typeof(NAspectRatioDropdown),
	typeof(NAspectRatioDropdownItem),
	typeof(NBackgroundModeHoverTip),
	typeof(NBackgroundModeTickbox),
	typeof(NBgmVolumeSlider),
	typeof(NCommonTooltipsHoverTip),
	typeof(NCommonTooltipsTickbox),
	typeof(NCreditsButton),
	typeof(NDisplayDropdown),
	typeof(NDisplayDropdownItem),
	typeof(NDropdownPositioner),
	typeof(NFastModeHoverTip),
	typeof(NFastModeTickbox),
	typeof(NFpsPaginator),
	typeof(NFullscreenHoverTip),
	typeof(NFullscreenTickbox),
	typeof(NHandCardCountHoverTip),
	typeof(NHandCardCountTickbox),
	typeof(NInputSettingsEntry),
	typeof(NInputSettingsPanel),
	typeof(NIntroLogoHoverTip),
	typeof(NIntroLogoTickbox),
	typeof(NLanguageButton),
	typeof(NLanguageDropdown),
	typeof(NLanguageDropdownItem),
	typeof(NLongPressConfirmationHoverTip),
	typeof(NLongPressConfirmationTickbox),
	typeof(NMasterVolumeSlider),
	typeof(NMsaaHoverTip),
	typeof(NMsaaPaginator),
	typeof(NMuteInBackgroundTickbox),
	typeof(NOpenFeedbackScreenButton),
	typeof(NOpenModdingScreenButton),
	typeof(NPaginateArrow),
	typeof(NPaginator),
	typeof(NResetGameplayButton),
	typeof(NResetGraphicsButton),
	typeof(NResetToDefaultControlsButton),
	typeof(NResetTutorialsButton),
	typeof(NResolutionDropdown),
	typeof(NResolutionDropdownItem),
	typeof(NRunTimerHoverTip),
	typeof(NRunTimerTickbox),
	typeof(NScreenshakeHoverTip),
	typeof(NScreenshakePaginator),
	typeof(NSettingsButton),
	typeof(NSettingsDropdown),
	typeof(NSettingsGradientMask),
	typeof(NSettingsPanel),
	typeof(NSettingsScreen),
	typeof(NSettingsSlider),
	typeof(NSettingsTab),
	typeof(NSettingsTabManager),
	typeof(NSettingsTickbox),
	typeof(NSettingsToast),
	typeof(NSfxVolumeSlider),
	typeof(NTextEffectsHoverTip),
	typeof(NTextEffectsTickbox),
	typeof(NUploadDataTickbox),
	typeof(NUploadGameplayDataHoverTip),
	typeof(NVSyncPaginator),
	typeof(NWindowResizeHoverTip),
	typeof(NWindowResizeTickbox),
	typeof(NFakeMerchantInventory),
	typeof(NMerchantCard),
	typeof(NMerchantCardRemoval),
	typeof(NMerchantCharacter),
	typeof(NMerchantDialogue),
	typeof(NMerchantHand),
	typeof(NMerchantInventory),
	typeof(NMerchantPotion),
	typeof(NMerchantRelic),
	typeof(NMerchantSlot),
	typeof(NAchievementHolder),
	typeof(NAchievementsGrid),
	typeof(NCharacterStats),
	typeof(NGeneralStatsGrid),
	typeof(NShareStatsButton),
	typeof(NStatEntry),
	typeof(NStatsScreen),
	typeof(NStatsTabManager),
	typeof(NAcknowledgeButton),
	typeof(NChapterPaginateButton),
	typeof(NCloseButton),
	typeof(NEpochCard),
	typeof(NEpochInspectScreen),
	typeof(NEpochPaginateButton),
	typeof(NEpochReminderText),
	typeof(NEpochSlot),
	typeof(NEraColumn),
	typeof(NResetProgressButton),
	typeof(NSlotsContainer),
	typeof(NTimelineLineMask),
	typeof(NTimelineScreen),
	typeof(NTimelineTutorial),
	typeof(NUnlockConfirmButton),
	typeof(NUnlockInfo),
	typeof(NUnlockCardsScreen),
	typeof(NUnlockCharacterScreen),
	typeof(NUnlockEpochScreen),
	typeof(NUnlockMiscScreen),
	typeof(NUnlockPotionsScreen),
	typeof(NUnlockRelicsScreen),
	typeof(NUnlockScreen),
	typeof(NUnlockTimelineScreen),
	typeof(NHandImage),
	typeof(NHandImageCollection),
	typeof(NTreasureRoomRelicCollection),
	typeof(NTreasureRoomRelicHolder),
	typeof(NRunTimer),
	typeof(NTopBarBossIcon),
	typeof(NTopBarButton),
	typeof(NTopBarDeckButton),
	typeof(NTopBarFloorIcon),
	typeof(NTopBarGold),
	typeof(NTopBarHp),
	typeof(NTopBarMapButton),
	typeof(NTopBarModifier),
	typeof(NTopBarPauseButton),
	typeof(NTopBarPortrait),
	typeof(NTopBarPortraitTip),
	typeof(NTopBarRoomIcon),
	typeof(NTreasureButton),
	typeof(NCeremonialBeastBgVfx),
	typeof(NKaiserCrabBossBackground),
	typeof(NQueenRepyBgVfx),
	typeof(NBolasVfx),
	typeof(NCardRareGlow),
	typeof(NCardUncommonGlow),
	typeof(NExhaustVfx),
	typeof(NFanOfKnivesVfx),
	typeof(NHellraiserAttackVfx),
	typeof(NHellraiserSwordVfx),
	typeof(NHellraiserVfx),
	typeof(NNightmareHandsVfx),
	typeof(NSpikeSplashVfx),
	typeof(NSpookyHandVfx),
	typeof(NSymbioteEyeMovementVfx),
	typeof(NGlowExampleVfx),
	typeof(NNoiseScroller),
	typeof(NSaturationExampleVfx),
	typeof(NAdditiveOverlayVfx),
	typeof(NAmalgamVfx),
	typeof(NArchitectVfx),
	typeof(NAxebotVfx),
	typeof(NBasicTrail),
	typeof(NBattlewornDummyVfx),
	typeof(NBezierTrail),
	typeof(NBgGroundSpikeVfx),
	typeof(NBigSlashImpactVfx),
	typeof(NBigSlashVfx),
	typeof(NBlockBrokenVfx),
	typeof(NBlockSparkVfx),
	typeof(NBounceSparkVfx),
	typeof(NCardEnchantVfx),
	typeof(NCardFlyPowerVfx),
	typeof(NCardFlyShuffleVfx),
	typeof(NCardFlyVfx),
	typeof(NCardSmithVfx),
	typeof(NCardTrail),
	typeof(NCardTrailVfx),
	typeof(NCardTransformVfx),
	typeof(NCardUpgradeVfx),
	typeof(NCeremonialBeastVfx),
	typeof(NCubexConstructVfx),
	typeof(NDaggerSprayFlurryVfx),
	typeof(NDaggerSprayImpactVfx),
	typeof(NDamageBlockedVfx),
	typeof(NDamageNumVfx),
	typeof(NDecimillipedeRocksVfx),
	typeof(NDecimillipedeSegmentVfx),
	typeof(NDesaturateTransitionVfx),
	typeof(NDevotedSculptorVfx),
	typeof(NDoomOverlayVfx),
	typeof(NDoomSubEmitterVfx),
	typeof(NDoomVfx),
	typeof(NEntomancerVfx),
	typeof(NEpochHighlightVfx),
	typeof(NEpochOffscreenVfx),
	typeof(NEpochSlotParticle),
	typeof(NFakeMerchantVfx),
	typeof(NFgGroundSpikeVfx),
	typeof(NFireBurningVfx),
	typeof(NFireBurstVfx),
	typeof(NFireSmokePuffVfx),
	typeof(NFlyconidSporesVfx),
	typeof(NFollowCursor),
	typeof(NFossilStalkerVfx),
	typeof(NFullscreenTextVfx),
	typeof(NFuzzyWurmCrawlerSpitTrailVfx),
	typeof(NGainEpochVfx),
	typeof(NGasBombVfx),
	typeof(NGaseousImpactVfx),
	typeof(NGoopyImpactVfx),
	typeof(NGroundFireVfx),
	typeof(NHauntedShipVfx),
	typeof(NHealNumVfx),
	typeof(NHeavyBluntVfx),
	typeof(NHitSparkVfx),
	typeof(NHorizontalLinesVfx),
	typeof(NHunterKillerVfx),
	typeof(NHyperbeamImpactVfx),
	typeof(NHyperbeamVfx),
	typeof(NItemThrowVfx),
	typeof(NKaiserCrabBossExplosionVfx),
	typeof(NKaiserCrabBossVfx),
	typeof(NKinFollowerVfx),
	typeof(NKinPriestBeamVfx),
	typeof(NKinPriestGrenadeVfx),
	typeof(NKinPriestVfx),
	typeof(NKnowledgeDemonVfx),
	typeof(NLargeMagicMissileVfx),
	typeof(NLaserVfx),
	typeof(NLineBurstVfx),
	typeof(NLiquidOverlayVfx),
	typeof(NLivingGasVfx),
	typeof(NLostAndForgottenVfx),
	typeof(NMapCircleVfx),
	typeof(NMapNodeSelectVfx),
	typeof(NMapPingVfx),
	typeof(NMechaKnightVfx),
	typeof(NMinionDiveBombVfx),
	typeof(NMirrorVfx),
	typeof(NMonsterDeathVfx),
	typeof(NMyteVfx),
	typeof(NNecrobinderFlameVfx),
	typeof(NOilSpillVfx),
	typeof(NParafrightVfx),
	typeof(NPhantasmalGardenerVfx),
	typeof(NPhrogParasiteVfx),
	typeof(NPoisonImpactVfx),
	typeof(NPotionFlashVfx),
	typeof(NPowerAppliedVfx),
	typeof(NPowerFlashVfx),
	typeof(NPowerRemovedVfx),
	typeof(NPowerUpVfx),
	typeof(NQueenVfx),
	typeof(NRadialBlurVfx),
	typeof(NRainVfx),
	typeof(NRegentVfx),
	typeof(NRelicFlashVfx),
	typeof(NRestSiteFireVfx),
	typeof(NRestSmokeVfx),
	typeof(NRollingBoulderVfx),
	typeof(NScratchVfx),
	typeof(NScreamVfx),
	typeof(NSeapunkVfx),
	typeof(NSewerClamVfx),
	typeof(NShivThrowVfx),
	typeof(NSleepingVfx),
	typeof(NSlimedBerserkerVfx),
	typeof(NSmallMagicMissileVfx),
	typeof(NSmokePuffVfx),
	typeof(NSmokyVignetteVfx),
	typeof(NSnappingJaxfruitVfx),
	typeof(NSoulFyshVfx),
	typeof(NSovereignBladeVfx),
	typeof(NSpectralKnightVfx),
	typeof(NSpeechBubbleVfx),
	typeof(NSpinyToadVfx),
	typeof(NSplashVfx),
	typeof(NSpookyScreamVfx),
	typeof(NSporeImpactVfx),
	typeof(NStabVfx),
	typeof(NStarryImpactVfx),
	typeof(NStunnedVfx),
	typeof(NSweepingBeamImpactVfx),
	typeof(NSweepingBeamVfx),
	typeof(NTestSubjectVfx),
	typeof(NTheInsatiableVfx),
	typeof(NTheObscuraVfx),
	typeof(NThinSliceVfx),
	typeof(NThoughtBubbleVfx),
	typeof(NUiFlashVfx),
	typeof(NVantomVfx),
	typeof(NVineShamblerVinesVfx),
	typeof(NWaterfallGiantVfx),
	typeof(NWormyImpactVfx),
	typeof(NEpochChains),
	typeof(NGaseousScreenVfx),
	typeof(NLowHpBorderVfx),
	typeof(LocalizedTexture),
	typeof(NHitStop),
	typeof(NParticlesContainer),
	typeof(NScreenShake),
	typeof(NSpriteAnimator),
	typeof(NTrail2D),
	typeof(NVfxParticleSystem),
	typeof(NVfxSpine),
	typeof(AbstractMegaRichTextEffect),
	typeof(RichTextAncientBanner),
	typeof(RichTextAqua),
	typeof(RichTextBlue),
	typeof(RichTextFadeIn),
	typeof(RichTextFlyIn),
	typeof(RichTextGold),
	typeof(RichTextGreen),
	typeof(RichTextJitter),
	typeof(RichTextOrange),
	typeof(RichTextPink),
	typeof(RichTextPurple),
	typeof(RichTextRed),
	typeof(RichTextSine),
	typeof(RichTextThinkyDots),
	typeof(TimelineInfoDumper),
	typeof(NGameInfoUploader)
})]
[assembly: AssemblyVersion("0.1.0.0")]
[module: RefSafetyRules(11)]
